version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing NestJS...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf *.json
      - rm -rf .gitignore
      - rm -rf *.md
      - |
        find ./ -mindepth 1 -maxdepth 1 -type d -not -name build \ 
          -exec rm -rf '{}' \;
      - mv build/* .

# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'