version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf *.json
      - rm -rf .gitignore
      - rm -rf *.md
      - rm -R node_modules
      - rm -R public
      - rm -R src
      - rm -R test
      - rm -R .git
      - mv build/* .

# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'